def build_html(games):
    with open('abc.html', 'w') as f:
        f.write('<!DOCTYPE html>\n')
        f.write('<html>\n')
        f.write('<head>\n')
        f.write('<title>Games Data</title>\n')
        f.write('<link rel="stylesheet" type="text/css" href="stylesheet.css">')
        f.write('</head>\n')
        f.write('<body>\n')
        f.write('<h1>Game Data</h1>\n')
        f.write('<hr>\n')
        f.write('<div>\n')
        f.write('<table id="table-1">\n')
        f.write('<tr>\n')
        f.write('<th>game_ID</th>\n')
        f.write('<th>title</th>\n')
        f.write('<th>price</th>\n')
        f.write('<th>CLS</th>\n')
        f.write('<th>release_date</th>\n')
        f.write('<th>in_Stock</th>\n')
        f.write('</tr>\n')
        write_game(games)
        f.write('</table>\n')
        f.write('</div>\n')
        f.write('</body>\n')

def write_game(self, games):
    for each in games:
        f.write('<tr class="game">\n')
        f.write('<td>' + each.game_id + '</td>\n')
        f.write('<td>' + each.name + '</td>\n')
        f.write('<td>' + each.price + '</td>\n')
        f.write('<td>' + each.classification + '</td>\n')
        f.write('<td>' + each.release_date + '</td>\n')
        f.write('<td>' + each.inStock + '</td>\n')
        f.write('</tr>\n')